In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.8.1'

In [3]:
torch.cuda.is_available()

True

In [4]:
!nvidia-smi

Fri May 14 18:14:52 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:03:00.0  On |                  N/A |
|  0%   31C    P8    35W / 300W |    764MiB / 11018MiB |     23%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
some_data = [[1,2,3],[5,6,7]]

In [6]:
np.array(some_data)==np.asarray(some_data)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [7]:
some_data = np.array(some_data)

In [8]:
some_data.dtype

dtype('int64')

In [9]:
sd = torch.tensor(some_data)

In [10]:
sd.dtype

torch.int64

In [11]:
np_arr = np.random.rand(3,4)
np_arr

array([[0.13162304, 0.20081296, 0.04979464, 0.35454584],
       [0.88155749, 0.00569282, 0.91820593, 0.13453379],
       [0.06701751, 0.78107064, 0.13339584, 0.80825352]])

In [12]:
t_arr = torch.from_numpy(np_arr)
t_arr

tensor([[0.1316, 0.2008, 0.0498, 0.3545],
        [0.8816, 0.0057, 0.9182, 0.1345],
        [0.0670, 0.7811, 0.1334, 0.8083]], dtype=torch.float64)

In [13]:
my_tensor = torch.rand(3,4)
my_tensor, my_tensor.dtype

(tensor([[0.1684, 0.8456, 0.8633, 0.0678],
         [0.1768, 0.1670, 0.5966, 0.7353],
         [0.5791, 0.7829, 0.7082, 0.1005]]),
 torch.float32)

In [14]:
my_tensor.device

device(type='cpu')

move tensor to GPU. this is not inplace operation

In [15]:
my_tensor.to('cuda')

tensor([[0.1684, 0.8456, 0.8633, 0.0678],
        [0.1768, 0.1670, 0.5966, 0.7353],
        [0.5791, 0.7829, 0.7082, 0.1005]], device='cuda:0')

In [16]:
!nvidia-smi

Fri May 14 18:15:02 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:03:00.0  On |                  N/A |
|  0%   33C    P2    64W / 300W |   1693MiB / 11018MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [17]:
my_tensor.device

device(type='cpu')

In [18]:
my_tensor = my_tensor.to('cuda')
my_tensor, my_tensor.device

(tensor([[0.1684, 0.8456, 0.8633, 0.0678],
         [0.1768, 0.1670, 0.5966, 0.7353],
         [0.5791, 0.7829, 0.7082, 0.1005]], device='cuda:0'),
 device(type='cuda', index=0))

In [19]:
my_tensor[:,1:3]

tensor([[0.8456, 0.8633],
        [0.1670, 0.5966],
        [0.7829, 0.7082]], device='cuda:0')

Elementwise multiplicatoin


In [20]:
my_tensor.mul(my_tensor)

tensor([[0.0284, 0.7151, 0.7453, 0.0046],
        [0.0313, 0.0279, 0.3560, 0.5407],
        [0.3353, 0.6129, 0.5015, 0.0101]], device='cuda:0')

In [21]:
my_tensor[0,1] = 1
my_tensor

tensor([[0.1684, 1.0000, 0.8633, 0.0678],
        [0.1768, 0.1670, 0.5966, 0.7353],
        [0.5791, 0.7829, 0.7082, 0.1005]], device='cuda:0')

In [22]:
my_tensor.mul(my_tensor)

tensor([[0.0284, 1.0000, 0.7453, 0.0046],
        [0.0313, 0.0279, 0.3560, 0.5407],
        [0.3353, 0.6129, 0.5015, 0.0101]], device='cuda:0')

In [23]:
torch.mul(my_tensor, 10)

tensor([[ 1.6838, 10.0000,  8.6331,  0.6778],
        [ 1.7683,  1.6703,  5.9662,  7.3534],
        [ 5.7907,  7.8290,  7.0819,  1.0048]], device='cuda:0')

In [24]:
torch.mul(my_tensor, torch.rand(3,3))

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [25]:
my_tensor.sum(axis=1), my_tensor.sum(axis=0)

(tensor([2.0995, 1.6758, 2.1706], device='cuda:0'),
 tensor([0.9243, 1.9499, 2.1681, 0.9036], device='cuda:0'))

In [26]:
my_tensor.matmul(my_tensor.T)

tensor([[1.7783, 0.7617, 1.4986],
        [0.7617, 0.9558, 0.7296],
        [1.4986, 0.7296, 1.4599]], device='cuda:0')

In [27]:
my_tensor @ my_tensor.T

tensor([[1.7783, 0.7617, 1.4986],
        [0.7617, 0.9558, 0.7296],
        [1.4986, 0.7296, 1.4599]], device='cuda:0')

In [28]:
torch.cat([my_tensor, my_tensor])

tensor([[0.1684, 1.0000, 0.8633, 0.0678],
        [0.1768, 0.1670, 0.5966, 0.7353],
        [0.5791, 0.7829, 0.7082, 0.1005],
        [0.1684, 1.0000, 0.8633, 0.0678],
        [0.1768, 0.1670, 0.5966, 0.7353],
        [0.5791, 0.7829, 0.7082, 0.1005]], device='cuda:0')

In [29]:
torch.cat([my_tensor, my_tensor], axis=1)

tensor([[0.1684, 1.0000, 0.8633, 0.0678, 0.1684, 1.0000, 0.8633, 0.0678],
        [0.1768, 0.1670, 0.5966, 0.7353, 0.1768, 0.1670, 0.5966, 0.7353],
        [0.5791, 0.7829, 0.7082, 0.1005, 0.5791, 0.7829, 0.7082, 0.1005]],
       device='cuda:0')

In [30]:
my_torch_soft_max = torch.nn.functional.softmax(my_tensor, dim=1)
my_torch_soft_max

tensor([[0.1612, 0.3702, 0.3229, 0.1457],
        [0.1901, 0.1883, 0.2893, 0.3323],
        [0.2510, 0.3078, 0.2856, 0.1556]], device='cuda:0')

In [31]:
my_torch_soft_max.sum(axis=1)

tensor([1., 1., 1.], device='cuda:0')

In [32]:
my_torch_soft_max.shape

torch.Size([3, 4])

In [33]:
my_torch_soft_max.size(), my_torch_soft_max.size(0), my_torch_soft_max.size(1)

(torch.Size([3, 4]), 3, 4)

How we deal with images,

`3 colors, 128x128 size and batches of 10 images`

In [34]:
torch.rand(10, 3, 128, 128)

tensor([[[[0.6470, 0.3641, 0.6088,  ..., 0.8420, 0.5253, 0.8625],
          [0.1326, 0.8770, 0.0509,  ..., 0.3974, 0.4584, 0.5773],
          [0.3959, 0.8803, 0.7951,  ..., 0.9637, 0.4336, 0.6368],
          ...,
          [0.6356, 0.7256, 0.2407,  ..., 0.1623, 0.8891, 0.6388],
          [0.8488, 0.9436, 0.4231,  ..., 0.8870, 0.3428, 0.6459],
          [0.2744, 0.7965, 0.4764,  ..., 0.3531, 0.2922, 0.8971]],

         [[0.1018, 0.1729, 0.8913,  ..., 0.7919, 0.6174, 0.9701],
          [0.7863, 0.9656, 0.6658,  ..., 0.9967, 0.3769, 0.7729],
          [0.0078, 0.6626, 0.4586,  ..., 0.8050, 0.8808, 0.6075],
          ...,
          [0.6809, 0.8988, 0.0020,  ..., 0.0333, 0.7637, 0.2135],
          [0.4738, 0.9228, 0.1563,  ..., 0.5053, 0.6638, 0.3003],
          [0.0501, 0.4705, 0.9697,  ..., 0.3486, 0.3547, 0.0727]],

         [[0.7664, 0.4436, 0.3738,  ..., 0.2971, 0.1187, 0.6274],
          [0.1775, 0.2674, 0.3361,  ..., 0.2841, 0.1589, 0.0787],
          [0.5443, 0.8800, 0.5281,  ..., 0

Clip function

In [82]:
my_tensor, my_tensor.clip(0.2, 0.8)

(tensor([[0.5259, 1.0000, 0.8152, 0.7808],
         [0.1176, 0.2853, 0.2082, 0.8577],
         [0.8421, 0.4149, 0.1887, 0.7761]], device='cuda:0'),
 tensor([[0.5259, 0.8000, 0.8000, 0.7808],
         [0.2000, 0.2853, 0.2082, 0.8000],
         [0.8000, 0.4149, 0.2000, 0.7761]], device='cuda:0'))

Move the tensor to CPU and detach

In [85]:
my_tensor.cpu().detach().numpy()

array([[0.5259323 , 1.        , 0.8152108 , 0.78080916],
       [0.11764795, 0.28530747, 0.2082004 , 0.85771906],
       [0.8421309 , 0.41489404, 0.18869781, 0.77610594]], dtype=float32)