In [1]:
from sklearn import preprocessing as pre
import numpy as np

In [2]:
dir(pre)

['Binarizer',
 'FunctionTransformer',
 'KBinsDiscretizer',
 'KernelCenterer',
 'LabelBinarizer',
 'LabelEncoder',
 'MaxAbsScaler',
 'MinMaxScaler',
 'MultiLabelBinarizer',
 'Normalizer',
 'OneHotEncoder',
 'OrdinalEncoder',
 'PolynomialFeatures',
 'PowerTransformer',
 'QuantileTransformer',
 'RobustScaler',
 'StandardScaler',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_csr_polynomial_expansion',
 '_data',
 '_discretization',
 '_encoders',
 '_function_transformer',
 '_label',
 'add_dummy_feature',
 'binarize',
 'label_binarize',
 'maxabs_scale',
 'minmax_scale',
 'normalize',
 'power_transform',
 'quantile_transform',
 'robust_scale',
 'scale']

In [3]:
data = np.random.normal(size=(4,4))
print(data)
pbin = pre.Binarizer(threshold=1.1)
pbin.fit(data)

pbin.transform(data)

[[-0.00826268 -0.02773459 -0.27677482 -0.36537191]
 [ 1.83697058  0.16420302 -0.39703839  0.90930123]
 [ 0.06806813 -1.0072467   0.08203432  1.11270613]
 [-0.15415872 -0.68738408 -0.33652924 -0.92110295]]


array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [4]:
data

array([[-0.00826268, -0.02773459, -0.27677482, -0.36537191],
       [ 1.83697058,  0.16420302, -0.39703839,  0.90930123],
       [ 0.06806813, -1.0072467 ,  0.08203432,  1.11270613],
       [-0.15415872, -0.68738408, -0.33652924, -0.92110295]])

In [6]:
data = np.array(list(map(str, range(9)))).reshape((3,3))
print(data)
p_oe = pre.OrdinalEncoder()
p_oe.fit(data)
test = [['0','4','8']]
print(test,'=',p_oe.transform(test))
test = [['6','1','5']]
print(test,'=',p_oe.transform(test))
test = [['6','1','7']]
print(test,'=',p_oe.transform(test))

[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']]
[['0', '4', '8']] = [[0. 1. 2.]]
[['6', '1', '5']] = [[2. 0. 1.]]


ValueError: Found unknown categories ['7'] in column 2 during transform

# OneHotEncoder

In [7]:


data = np.array(list(map(str, range(9)))).reshape((3,3))
print(data)
p_ohe = pre.OneHotEncoder(handle_unknown='ignore')
p_ohe.fit(data)

print('Categories',p_ohe.categories_)

test = [['0','4','8']]
print(test,'=',p_ohe.transform(test))
print(test,'=',p_ohe.transform(test).toarray())

test = [['0','7','8']]
print(test,'=',p_ohe.transform(test))
print(test,'=',p_ohe.transform(test).toarray())


test = [['6','1','5']]
print(test,'=',p_ohe.transform(test))
print(test,'=',p_ohe.transform(test).toarray())
# wrong category
test = [['6','1','7'],['6','1','8']]
print(test,'=',p_ohe.transform(test))
print(test,'=\n',p_ohe.transform(test).toarray())

[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']]
Categories [array(['0', '3', '6'], dtype='<U1'), array(['1', '4', '7'], dtype='<U1'), array(['2', '5', '8'], dtype='<U1')]
[['0', '4', '8']] =   (0, 0)	1.0
  (0, 4)	1.0
  (0, 8)	1.0
[['0', '4', '8']] = [[1. 0. 0. 0. 1. 0. 0. 0. 1.]]
[['0', '7', '8']] =   (0, 0)	1.0
  (0, 5)	1.0
  (0, 8)	1.0
[['0', '7', '8']] = [[1. 0. 0. 0. 0. 1. 0. 0. 1.]]
[['6', '1', '5']] =   (0, 2)	1.0
  (0, 3)	1.0
  (0, 7)	1.0
[['6', '1', '5']] = [[0. 0. 1. 1. 0. 0. 0. 1. 0.]]
[['6', '1', '7'], ['6', '1', '8']] =   (0, 2)	1.0
  (0, 3)	1.0
  (1, 2)	1.0
  (1, 3)	1.0
  (1, 8)	1.0
[['6', '1', '7'], ['6', '1', '8']] =
 [[0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 1.]]


# LabelEncoder

In [8]:
chr(97)

'a'

In [13]:
chrs = lambda x: chr(97+x)
data = np.array(list(map(chrs, range(9)))+list(map(chrs, range(9))))[::-1]
print(data)
p_le = pre.LabelEncoder()
p_le.fit(data)

print('Classes',p_le.classes_)

test = ['a','b','g','f']
print(test,'=',p_le.transform(test))

test = []
print(test,'=',p_le.transform(test))
# wrong category

['i' 'h' 'g' 'f' 'e' 'd' 'c' 'b' 'a' 'i' 'h' 'g' 'f' 'e' 'd' 'c' 'b' 'a']
Classes ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i']
['a', 'b', 'g', 'f'] = [0 1 6 5]
[] = []


In [14]:
dir(p_le)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_n_features',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_validate_data',
 'classes_',
 'fit',
 'fit_transform',
 'get_params',
 'inverse_transform',
 'set_params',
 'transform']

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(list(range(10)), columns=['a'])

In [ ]:
df

In [ ]:
df.a.isin()