In [6]:
from sklearn import preprocessing as pre
import numpy as np

In [4]:
dir(pre)

['Binarizer',
 'FunctionTransformer',
 'KBinsDiscretizer',
 'KernelCenterer',
 'LabelBinarizer',
 'LabelEncoder',
 'MaxAbsScaler',
 'MinMaxScaler',
 'MultiLabelBinarizer',
 'Normalizer',
 'OneHotEncoder',
 'OrdinalEncoder',
 'PolynomialFeatures',
 'PowerTransformer',
 'QuantileTransformer',
 'RobustScaler',
 'StandardScaler',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_csr_polynomial_expansion',
 '_data',
 '_discretization',
 '_encoders',
 '_function_transformer',
 '_label',
 'add_dummy_feature',
 'binarize',
 'label_binarize',
 'maxabs_scale',
 'minmax_scale',
 'normalize',
 'power_transform',
 'quantile_transform',
 'robust_scale',
 'scale']

In [20]:
data = np.random.normal(size=(4,4))
print(data)
pbin = pre.Binarizer(threshold=1.1)
pbin.fit(data)

pbin.transform(data)

[[-1.3930076  -0.24662144  0.51273732 -0.08422551]
 [-0.78965887 -0.39500978  0.57652038  0.64641968]
 [ 1.20981958  0.60662667 -0.27244625  0.07309431]
 [-0.37686842 -1.23891013 -0.70228065  0.55159605]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
data

array([[-1.3930076 , -0.24662144,  0.51273732, -0.08422551],
       [-0.78965887, -0.39500978,  0.57652038,  0.64641968],
       [ 1.20981958,  0.60662667, -0.27244625,  0.07309431],
       [-0.37686842, -1.23891013, -0.70228065,  0.55159605]])

In [22]:
list(map(str(data)))

TypeError: map() must have at least two arguments.

In [35]:
data = np.array(list(map(str, range(9)))).reshape((3,3))
print(data)
p_oe = pre.OrdinalEncoder()
p_oe.fit(data)
test = [['0','4','8']]
print(test,'=',p_oe.transform(test))
test = [['6','1','5']]
print(test,'=',p_oe.transform(test))
test = [['6','1','7']]
print(test,'=',p_oe.transform(test))

[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']]
[['0', '4', '8']] = [[0. 1. 2.]]
[['6', '1', '5']] = [[2. 0. 1.]]


ValueError: Found unknown categories ['7'] in column 2 during transform

# OneHotEncoder

In [53]:


data = np.array(list(map(str, range(9)))).reshape((3,3))
print(data)
p_ohe = pre.OneHotEncoder(handle_unknown='ignore')
p_ohe.fit(data)

print('Categories',p_ohe.categories_)

test = [['0','4','8']]
print(test,'=',p_ohe.transform(test))
print(test,'=',p_ohe.transform(test).toarray())

test = [['0','7','8']]
print(test,'=',p_ohe.transform(test))
print(test,'=',p_ohe.transform(test).toarray())


test = [['6','1','5']]
print(test,'=',p_ohe.transform(test))
print(test,'=',p_ohe.transform(test).toarray())
# wrong category
test = [['6','1','7'],['6','1','8']]
print(test,'=',p_ohe.transform(test))
print(test,'=\n',p_ohe.transform(test).toarray())

[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']]
Categories [array(['0', '3', '6'], dtype='<U1'), array(['1', '4', '7'], dtype='<U1'), array(['2', '5', '8'], dtype='<U1')]
[['0', '4', '8']] =   (0, 0)	1.0
  (0, 4)	1.0
  (0, 8)	1.0
[['0', '4', '8']] = [[1. 0. 0. 0. 1. 0. 0. 0. 1.]]
[['0', '7', '8']] =   (0, 0)	1.0
  (0, 5)	1.0
  (0, 8)	1.0
[['0', '7', '8']] = [[1. 0. 0. 0. 0. 1. 0. 0. 1.]]
[['6', '1', '5']] =   (0, 2)	1.0
  (0, 3)	1.0
  (0, 7)	1.0
[['6', '1', '5']] = [[0. 0. 1. 1. 0. 0. 0. 1. 0.]]
[['6', '1', '7'], ['6', '1', '8']] =   (0, 2)	1.0
  (0, 3)	1.0
  (1, 2)	1.0
  (1, 3)	1.0
  (1, 8)	1.0
[['6', '1', '7'], ['6', '1', '8']] =
 [[0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 1.]]


# LabelEncoder

In [66]:
chr(97)

'a'

In [68]:
chrs = lambda x: chr(97+x)
data = np.array(list(map(chrs, range(9)))+list(map(chrs, range(9))))[::-1]
print(data)
p_ohe = pre.LabelEncoder()
p_ohe.fit(data)

print('Classes',p_ohe.classes_)

test = ['a','b','g','f']
print(test,'=',p_ohe.transform(test))

test = ['0','7','8','1']
print(test,'=',p_ohe.transform(test))

test = []
print(test,'=',p_ohe.transform(test))
# wrong category

['i' 'h' 'g' 'f' 'e' 'd' 'c' 'b' 'a' 'i' 'h' 'g' 'f' 'e' 'd' 'c' 'b' 'a']
Classes ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i']
['a', 'b', 'g', 'f'] = [0 1 6 5]


ValueError: y contains previously unseen labels: '0'

In [69]:
import pandas as pd

In [72]:
df = pd.DataFrame(list(range(10)), columns=['a'])

In [73]:
df

a
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

In [ ]:
df.a.isin()